Day9/MobileStore/MobileStore/Models/Customer.cs
namespace MobileStore.Models;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;


public class Customer
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int MobileNo { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }

    public Customer()
    {

    }

    public Customer(string fn, string ln, int mobNo, string email, string pass)
    {
        this.FirstName = fn;
        this.LastName = ln;
        this.MobileNo = mobNo;
        this.Email = email;
        this.Password = pass;
    }

    public static void Serial(List<Customer> cust)
    {
        cust.ForEach(c => Console.WriteLine(c));
        try
        {
            var options = new JsonSerializerOptions { IncludeFields = true };
            var custJson = JsonSerializer.Serialize<List<Customer>>(cust, options);
            string fileName = @"C:\.NET\dotnet\Day9\Customer.json";
            File.WriteAllText(fileName, custJson);
        }
        catch (Exception e)
        {
            Console.WriteLine("Error => " + e);
        }
    }

    public static List<Customer> Dser()
    {
        List<Customer> li = new List<Customer>();
        string fileName = @"C:\.NET\dotnet\Day9\Customer.json";
        string jsonString = File.ReadAllText(fileName);
        if (jsonString == "")
            return null;

        li = JsonSerializer.Deserialize<List<Customer>>(jsonString);
        return li;
    }

}

Day9/MobileStore/MobileStore/Models/ErrorViewModel.cs
namespace MobileStore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Day9/MobileStore/MobileStore/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MobileStore.Models;

namespace MobileStore.Controllers;

public class AuthController : Controller
{
    private readonly ILogger<AuthController> _logger;

    public AuthController(ILogger<AuthController> logger)
    {
        _logger = logger;
    }
    
    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    public IActionResult postRegistration(string fname,string lname,int mob,string email,string pass){
        Console.WriteLine("Insert data in json on acton registrstion.");
        List<Customer> li=new List<Customer>();
        li=Customer.Dser();
        if(li[0]!=null)
        foreach(Customer s in li){
            if(s.Email==email){
                return Redirect("/auth/Registration");
            }   
        }
        li.Add(new Customer(fname,lname,mob,email,pass));
        Customer.Serial(li);
        return Redirect("/auth/Login");
        //return View();
    } 

    public IActionResult Validate(string email, string password)
    {
         Console.WriteLine("Validating User credentials.... ");
        List<Customer> li=Customer.Dser();
        if(li!=null)
        foreach(Customer c in li){
            if(c.Email==email && c.Password==password){
                return Redirect("/home/IACSD");
            }
        }
        return Redirect("/auth/Welcome");

        Console.WriteLine("Validate Credentials... ");
        if(email == "palashkardhekar5@gmail.com" && password == "palash"){
            Console.WriteLine("Customer is valid");
            return Redirect("/auth/Welcome");
        }
        return View();
    }

    public IActionResult Welcome()
    {
        Console.WriteLine("Invoking Home Controller Welcome method. ");
        return View();
    }

    public IActionResult Registration()
    {
        Console.WriteLine("Invoking Home Controller Registration method. ");
        return View();
    }



    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day9/MobileStore/MobileStore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MobileStore.Models;

namespace MobileStore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day9/MobileStore/MobileStore/Views/Customer/Customer.cshtml
@{
    ViewData["Title"] = "Customer Detail Page";
}

<div class="text-center">
    <h1>All Customer Details</h1>
    <hr/>
    <div>
        @* @{
            List<Customer> allCustomer = (List<Customer>)ViewData["catalog"];
                <ol>
                    @foreach (Customer cust in allCustomer)
                    {
                        <li>@cust.FirstName</li>
                    }
                </ol>
        } *@
    </div>
</div>

Day9/MobileStore/MobileStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MobileStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MobileStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MobileStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Registration">Registration</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Customer">Customer Info</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MobileStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>